# Generated by Django 3.1.5 on 2021-01-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitems',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
